Numpy array

In [1]:
lst = [1,2,4,5,6]

In [2]:
import numpy as np

In [3]:
np.array(lst)

array([1, 2, 4, 5, 6])

In [5]:
new_lst= [[1,2,3],[4,5,7],[2,7,0]]

In [7]:
x = np.array(new_lst)

In [8]:
x

array([[1, 2, 3],
       [4, 5, 7],
       [2, 7, 0]])

In [9]:
np.arange(0,10) #same as range method but with using Numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3) #method of all zeros

array([0., 0., 0.])

In [12]:
np.zeros((5,5)) #passing a tuple 5,5 inside it 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros([5,5]) #passing a list 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4) # 1D array matrix

array([1., 1., 1., 1.])

In [17]:
np.ones((7,3)) # 2D matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.eye(4) #square matrix with 1 in the middel

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.23515396, 0.02094427, 0.37379976, 0.16739968, 0.7088462 ])

In [23]:
np.random.randn(5)

array([ 0.29519748,  1.50866286,  0.21647235, -0.82945912, -0.42956377])

In [24]:
np.random.randint(0,100) #output is random number between 0 to 100 
# 0 inclusive but 100 is not which means 100 won't be the output only from 0-99

90

In [38]:
arr = np.arange (0,16) #ينفع اذا حطيت الريشيب في مضروب العدد يعني ٤ في ٤ ب١٦ او رينج ٢٥ واخلي الريشيب ٥ و٥

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
xarray = np.random.randint(0,50,10)

In [43]:
xarray

array([ 2, 41, 25, 48, 44, 45, 20, 37, 22,  6])

In [44]:
xarray.max() #maxuim number in array

48

In [45]:
xarray.min()

2

In [46]:
xarray.argmax() #to find the the number of index of the maxuim number in array

3

In [47]:
xarray.argmin() #to find the the number of index of the min number in array

0

In [48]:
arr.shape # 1D 

(16,)

In [49]:
arr = arr.reshape(4,4)

In [50]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
arr.shape #2D have reshaped it

(4, 4)

In [53]:
arr.dtype #to know the data type of an array

dtype('int64')

In [54]:
xarray.dtype

dtype('int64')

In [55]:
from numpy.random import randint

In [57]:
randint(2,10)

6

Numpy Array indexing 

In [58]:
import numpy as np

In [59]:
darray = np.arange(1,10)

In [60]:
darray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
darray[0] #requesting to print the value in index 0 of the array

1

In [62]:
darray [1:6] #requesting to print the values from index 1 to 6

array([2, 3, 4, 5, 6])

In [63]:
darray[:6] #requesting to print the values from index 1 to 6 but without writting 1 
#both ways are right 

array([1, 2, 3, 4, 5, 6])

In [65]:
array_2d = np.array ([[1,3,4],[7,4,6],[49,40,22]])

In [66]:
array_2d

array([[ 1,  3,  4],
       [ 7,  4,  6],
       [49, 40, 22]])

In [68]:
array_2d[1][1] #calling an element from 2D array with dobule method

4

In [70]:
array_2d[2][2]

22

In [71]:
array_2d[2,2] #single brakets method calling an element from 2D array

22

In [72]:
array_2d[:2,1:]

array([[3, 4],
       [4, 6]])

In [81]:
array_2d[:2,0:]


array([[1, 3, 4],
       [7, 4, 6]])

In [82]:
bool_array = darray > 5 #we compare the entire array with 5 and save it in veriable bool_arr

In [83]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True])

In [84]:
darray[bool_array] #it will retrive the true values only

array([6, 7, 8, 9])

In [85]:
darray[darray>5] #shortcut to the same steps before

array([6, 7, 8, 9])

In [86]:
array_2d[array_2d==40]

array([40])

In [91]:
warray = np.arange(50).reshape(5,10)

In [93]:
warray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
warray[2,4:7]

array([24, 25, 26])

Numpy Operation

In [97]:
import numpy as np

In [98]:
ta = np.arange(0,11)

In [99]:
ta

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
ta + ta

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
ta * ta

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
ta ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
ta + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [104]:
ta/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [105]:
ta - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [106]:
ta / 0 #in numpy array doesn't give an error when divied 0/0 in index 0 instaed gives nan

<ipython-input-106-ef7d1a26a66b>:1: RuntimeWarning: divide by zero encountered in true_divide
  ta / 0
<ipython-input-106-ef7d1a26a66b>:1: RuntimeWarning: invalid value encountered in true_divide
  ta / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

Universal Array Functions

https://numpy.org/doc/stable/reference/ufuncs.html

In [107]:
np.exp(ta)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [108]:
np.sqrt(ta)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [109]:
np.log(ta)

<ipython-input-109-2f4064b465dd>:1: RuntimeWarning: divide by zero encountered in log
  np.log(ta)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [110]:
np.max(ta)

10

In [112]:
ta.max() #calling the method

10

In [113]:
np.sign(ta)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [114]:
np.sin(ta)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])